export default {
  input: 'dist/lib/index.js',
  output: {
    file: 'dist/bundles/ngx-markdown.umd.js',
    format: 'umd',
  },
  sourceMap: false,
  name: 'ngx.markdown',
  globals: {
    '@angular/core': 'ng.core',
    '@angular/http': 'ng.http',
    'marked': 'marked',
    'prismjs': 'prismjs',
    'rxjs/Observable': 'rx.observable',
    'rxjs/observable/ErrorObservable': 'rx.errorObservable',
  },
  external: [
    '@angular/core',
    '@angular/http',
    'marked',
    'prismjs',
    'prismjs/prism',
    'prismjs/components/prism-c',
    'prismjs/components/prism-cpp',
    'prismjs/components/prism-csharp',
    'prismjs/components/prism-css',
    'prismjs/components/prism-diff',
    'prismjs/components/prism-java',
    'prismjs/components/prism-javascript',
    'prismjs/components/prism-perl',
    'prismjs/components/prism-php',
    'prismjs/components/prism-python',
    'prismjs/components/prism-sass',
    'prismjs/components/prism-scss',
    'prismjs/components/prism-typescript',
    'rxjs/Observable',
    'rxjs/observable/ErrorObservable',
    'rxjs/add/operator/catch',
    'rxjs/add/operator/map',
  ],
}